export const DARK_MODE = 'DARK_MODE'

export const GET_COUNTRIES = 'GET_COUNTRIES'
export const CHANGE_LOADING = 'CHANGE_LOADING'
export const GET_COUNTRIES_NAME = 'GET_COUNTRIES_NAME'
export const GET_COUNTRIES_REGION = 'GET_COUNTRIES_REGION'
export const GET_COUNTRY_NAME = 'GET_COUNTRY_NAME'
export const GET_COUNTRIES_ERROR = 'GET_COUNTRIES_ERROR'